/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
export { }

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
